### ISSUE TITLE
Link to source from google play is broken when viewed from google play app

### ISSUE THREAD

**Issue by PowerUser64** [MateusRodCosta/vidya_music#19]
The link to the source in the description of Vidya Music on google play is broken when viewed in the google play mobile app. The problem is the `.` at the end is considered part of the URL, [which makes it lead to a 404 page](https://github.com/MateusRodCosta/vidya_music.).

Screenshot:
<img src="https://github.com/MateusRodCosta/vidya_music/assets/24578572/e827372c-4246-4279-92c9-b429bde4df33" width="500" display="block" margin-left="auto" margin-right="auto" />

A way to fix this could be to write the final sentence of the description on its own line, so it looks something like this:
```
Source: https://github.com/MateusRodCosta/vidya_music
```

This avoids placing punctuation at the end of the URL.

**Comment by MateusRodCosta** [comment]
Yeah, for some reason it works fine on the Web version but not in the Google Play app.

I am the type of person who always puts a space between link and punctuation, but this time I didn't.
I will fix this soon.

**Comment by MateusRodCosta** [comment]
Should be solved.
